remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "mint"
title: Christopher Bowcutt's Blog

url: "/cbowcutt.github.io"
baseurl: "/cbowcutt.github.io"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

author:
  name             : "Christopher Bowcutt"
  avatar           : "/assets/images/avatar_sbarro.jpg"
  github           : "cbowcutt"
  linkedin         : "christopher-bowcutt-4b691887"
  
  
sass:
  sass_dir: _sass
  
images:
  GeneralizedStateMachine : "/assets/images/GeneralizedStateMachine.png"
  ManualStateMachine      : "/assets/images/ManualStateMachine.png"
  AutoStoreStateMachine   : "/assets/images/AutoStoreStateMachine.png"
  
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
    - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
